name: "Sanity Test"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  make_build:
    name: "make build"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Set up Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: "Get dependencies"
        run: "go get -v -t ./..."

      - name: "Run the tests"
        run: "make test"

      - name: "Build binary"
        run: "make build"

